//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace student_apis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT1
    {
        public int STD_ID { get; set; }
        public string STD_NAME { get; set; }
        public string COURSES { get; set; }
        public Nullable<System.DateTime> STD_DOB { get; set; }
        public string CREATED_BY { get; set; }
        public string MODIFED_BY { get; set; }
        public Nullable<bool> STD_ISDELETED { get; set; }
    }
}
